# Generated by Django 5.1 on 2025-02-17 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagelearncontent',
            old_name='learn_content',
            new_name='content',
        ),
    ]
