# Generated by Django 5.1 on 2025-06-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_app', '0003_chartdata_chatmessage_claudeimage_gptimage_newissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartdata',
            name='claude_solved_list',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chartdata',
            name='gpt_solved_list',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chartdata',
            name='key_issues',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
