# Generated by Django 5.1 on 2025-06-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_app', '0004_chartdata_claude_solved_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='issues',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='NewIssue',
        ),
    ]
