# Generated by Django 5.1 on 2025-07-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_app', '0005_chatmessage_issues_delete_newissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='claudeimage',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='claude/'),
        ),
        migrations.AddField(
            model_name='gptimage',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='gpt/'),
        ),
    ]
