# Generated by Django 5.1 on 2025-07-01 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart_app', '0006_claudeimage_image_file_gptimage_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claudeimage',
            name='image_base64',
        ),
        migrations.RemoveField(
            model_name='gptimage',
            name='image_base64',
        ),
    ]
