# Generated by Django 5.1 on 2025-06-19 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_app', '0002_rename_learn_content_imagelearncontent_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.URLField()),
                ('key_issues', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='chart_app.chartdata')),
            ],
        ),
        migrations.CreateModel(
            name='ClaudeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_base64', models.TextField()),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claude_images', to='chart_app.chartdata')),
            ],
        ),
        migrations.CreateModel(
            name='GptImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_base64', models.TextField()),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpt_images', to='chart_app.chartdata')),
            ],
        ),
        migrations.CreateModel(
            name='NewIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_key', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_issues', to='chart_app.chatmessage')),
            ],
        ),
    ]
